import type {
  CourseType,
  EnrolledCourseType,
  MinimalCourseDisplay,
} from '@/types/Courses/CourseType';

export const courses: CourseType[] = [
  {
    _id: '68632f4ef9062aec78934b21',
    title: 'Desarrollo Web Full Stack con React y Node.js',
    description:
      'Aprende a crear aplicaciones web completas desde cero con las tecnologías más demandadas del mercado.',
    instructor: 'María González',
    price: 89.99,
    originalPrice: 129.99,
    rating: 4.8,
    students: 2847,
    duration: '42 horas',
    lessons: 156,
    level: 'Intermedio',
    category: 'Desarrollo Web',
    image: 'https://picsum.photos/300/200',
    tags: ['React', 'Node.js', 'JavaScript', 'MongoDB'],
  },
  {
    _id: '2',
    title: 'Diseño UX/UI con Figma',
    description:
      'Domina los principios del diseño de experiencia de usuario y crea interfaces atractivas y funcionales.',
    instructor: 'Carlos Ruiz',
    price: 69.99,
    originalPrice: 99.99,
    rating: 4.9,
    students: 1923,
    duration: '28 horas',
    lessons: 89,
    level: 'Principiante',
    category: 'Diseño',
    image: 'https://picsum.photos/300/200',
    tags: ['Figma', 'UX', 'UI', 'Prototipado'],
  },
  {
    _id: '3',
    title: 'Python para Data Science',
    description:
      'Aprende análisis de datos, machine learning y visualización con Python y sus librerías más populares.',
    instructor: 'Ana Martínez',
    price: 94.99,
    originalPrice: 149.99,
    rating: 4.7,
    students: 3156,
    duration: '55 horas',
    lessons: 203,
    level: 'Intermedio',
    category: 'Data Science',
    image: 'https://picsum.photos/300/200',
    tags: ['Python', 'Pandas', 'NumPy', 'Machine Learning'],
  },
  {
    _id: '4',
    title: 'Marketing Digital y Redes Sociales',
    description:
      'Estrategias efectivas para hacer crecer tu negocio en el mundo digital y redes sociales.',
    instructor: 'Luis Fernández',
    price: 59.99,
    originalPrice: 89.99,
    rating: 4.6,
    students: 4521,
    duration: '35 horas',
    lessons: 124,
    level: 'Principiante',
    category: 'Marketing',
    image: 'https://picsum.photos/300/200',
    tags: ['SEO', 'SEM', 'Social Media', 'Analytics'],
  },
  {
    _id: '5',
    title: 'Desarrollo de Apps Móviles con React Native',
    description:
      'Crea aplicaciones móviles nativas para iOS y Android usando React Native y JavaScript.',
    instructor: 'Pedro Sánchez',
    price: 79.99,
    originalPrice: 119.99,
    rating: 4.5,
    students: 1687,
    duration: '38 horas',
    lessons: 142,
    level: 'Avanzado',
    category: 'Desarrollo Móvil',
    image: 'https://picsum.photos/300/200',
    tags: ['React Native', 'Mobile', 'iOS', 'Android'],
  },
  {
    _id: '6',
    title: 'Fotografía Digital Profesional',
    description:
      'Técnicas avanzadas de fotografía digital, composición, iluminación y edición profesional.',
    instructor: 'Laura Torres',
    price: 74.99,
    originalPrice: 109.99,
    rating: 4.8,
    students: 2234,
    duration: '31 horas',
    lessons: 98,
    level: 'Intermedio',
    category: 'Fotografía',
    image: 'https://picsum.photos/300/200',
    tags: ['Fotografía', 'Lightroom', 'Photoshop', 'Composición'],
  },
];

export const enrolledCourses: EnrolledCourseType[] = [
  {
    _id: '68632f4ef9062aec78934b21',
    title: 'Desarrollo Web Full Stack con React y Node.js',
    description:
      'Aprende a crear aplicaciones web completas desde cero con las tecnologías más demandadas del mercado.',
    instructor: 'María González',
    price: 89.99,
    originalPrice: 129.99,
    students: 2847,
    duration: '42 horas',
    level: 'Intermedio',
    tags: ['React', 'Node.js', 'JavaScript', 'MongoDB'],
    image: 'https://picsum.photos/300/200',
    progress: 75,
    lessons: 156,
    completedLessons: 117,
    lastAccessed: 'Hace 2 días',
    status: 'En progreso',
    category: 'Desarrollo Web',
    rating: 4.8,
    nextLesson: 'Autenticación con JWT',
  },
  {
    _id: '68632f4ef9062aec78934b22',
    title: 'Diseño UX/UI con Figma',
    description:
      'Domina los principios del diseño de experiencia de usuario y crea interfaces atractivas y funcionales.',
    instructor: 'Carlos Ruiz',
    price: 69.99,
    originalPrice: 99.99,
    students: 1923,
    duration: '28 horas',
    level: 'Principiante',
    tags: ['Figma', 'UX', 'UI', 'Prototipado'],
    image: 'https://picsum.photos/300/200',
    progress: 100,
    lessons: 89,
    completedLessons: 89,
    lastAccessed: 'Hace 1 semana',
    status: 'Completado',
    category: 'Diseño',
    rating: 4.9,
  },
  {
    _id: '68632f4ef9062aec78934b23',
    title: 'Python para Data Science',
    description:
      'Aprende análisis de datos, machine learning y visualización con Python y sus librerías más populares.',
    instructor: 'Ana Martínez',
    price: 94.99,
    originalPrice: 149.99,
    students: 3156,
    duration: '55 horas',
    level: 'Intermedio',
    tags: ['Python', 'Pandas', 'NumPy', 'Machine Learning'],
    image: 'https://picsum.photos/300/200',
    progress: 45,
    lessons: 203,
    completedLessons: 91,
    lastAccessed: 'Hace 3 días',
    status: 'En progreso',
    category: 'Data Science',
    rating: 4.7,
    nextLesson: 'Análisis exploratorio de datos',
  },
  {
    _id: '68632f4ef9062aec78934b24',
    title: 'Marketing Digital y Redes Sociales',
    description:
      'Estrategias efectivas para hacer crecer tu negocio en el mundo digital y redes sociales.',
    instructor: 'Luis Fernández',
    price: 59.99,
    originalPrice: 89.99,
    students: 4521,
    duration: '35 horas',
    level: 'Principiante',
    tags: ['SEO', 'SEM', 'Social Media', 'Analytics'],
    image: 'https://picsum.photos/300/200',
    progress: 100,
    lessons: 124,
    completedLessons: 124,
    lastAccessed: 'Hace 5 días',
    status: 'Completado',
    category: 'Marketing',
    rating: 4.6,
    certificateId: 'CERT-MKT-2024-002',
  },
  {
    _id: '68632f4ef9062aec78934b26',
    title: 'Fotografía Digital Profesional',
    description:
      'Técnicas avanzadas de fotografía digital, composición, iluminación y edición profesional.',
    instructor: 'Laura Torres',
    price: 74.99,
    originalPrice: 109.99,
    students: 2234,
    duration: '31 horas',
    level: 'Intermedio',
    tags: ['Fotografía', 'Lightroom', 'Photoshop', 'Composición'],
    image: 'https://picsum.photos/300/200',
    progress: 20,
    lessons: 98,
    completedLessons: 20,
    lastAccessed: 'Hace 1 día',
    status: 'En progreso',
    category: 'Fotografía',
    rating: 4.8,
    nextLesson: 'Composición y regla de tercios',
  },
];

export const courseRecommendations: MinimalCourseDisplay[] = [
  {
    id: '1',
    title: 'Fundamentos de HTML y CSS',
    description: 'Aprende las bases del desarrollo web con HTML5 y CSS3',
    level: 'Principiante',
    duration: '4 semanas',
    tags: [
      'HTML5 semántico',
      'CSS Grid y Flexbox',
      'Responsive Design',
      'Accesibilidad web',
    ],
    minScore: 0,
    category: 'HTML',
  },
  {
    id: '4',
    title: 'JavaScript Avanzado y Frameworks',
    description: 'Conceptos avanzados y frameworks modernos de JavaScript',
    level: 'Avanzado',
    duration: '8 semanas',
    tags: ['Async/Await', 'Webpack', 'React/Vue.js', 'Node.js'],
    minScore: 80,
    category: 'JavaScript',
  },
];

export function toMinimalCourseDisplay(
  course: CourseType,
): MinimalCourseDisplay {
  return {
    id: course._id,
    title: course.title,
    description: course.description,
    level: course.level,
    duration: course.duration,
    tags: course.tags,
    minScore: 0,
    category: course.category,
  };
}
